#!/usr/bin/env python3
"""Model and firmware test data for isolde/sw/onnx_transformer.

Writes one transformer block of generate_transformer.py (a copy of
onnx-mlir's test-isolde/transformer/models/generate_transformer.py; keep it
in sync) as an ONNX model and, from the same weights and input, the data
main.c checks the RTL against:

    inc/tf_input.h    tf_input[12 * IN_COLS]  the graph input, row-major
    inc/tf_golden.h   tf_golden[12 * 16]      bit-exact RedMulE FP16 result
    inc/tensor_dim.h  FRAMES, IN_COLS, D_MODEL, D_FF, BLOCK_NAME

BLOCK (--block) is one of

    layer       h + MHA(h), then + FFN   (EncoderLayer, the default)
    mha         h + MultiHeadAttention(h, h)
    ffn         h + PositionwiseFeedForward(h)
    proj        window[12,32] . Wproj + P
    proj_layer  proj, then EncoderLayer

The golden is generate_transformer.redmule_reference: the schedule onnx-mlir
emits, with RedMulE arithmetic (FP16 rounding after each of the 16
reduction steps, radar_attention/tformer.py).

Weights and input:
  --seed N              random, as generate_transformer.py (default 0)
  --weights W --vectors V
                        the trained radar_attention encoder (layer 0 of
                        tformer_weights.h, already folded: scale = post_scale
                        = 1).  The input is the firmware's value at the
                        block's entry (tf_features window, tf_golden_proj or
                        tf_golden_l0_attn_out of tformer_vectors.h), and the
                        golden must equal the firmware's value at its exit
                        (tf_golden_proj, tf_golden_l0_attn_out or
                        tf_golden_l0_out) bit for bit, else this script
                        stops.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import numpy as np
import onnx

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate_transformer as G  # noqa: E402

L, D, F = G.L, G.D, G.F

# block -> (firmware value at the input, firmware value at the output)
FIRMWARE_STAGES = {
    "proj": ("tf_features", "tf_golden_proj"),
    "proj_layer": ("tf_features", "tf_golden_l0_out"),
    "layer": ("tf_golden_proj", "tf_golden_l0_out"),
    "mha": ("tf_golden_proj", "tf_golden_l0_attn_out"),
    "ffn": ("tf_golden_l0_attn_out", "tf_golden_l0_out"),
}


# ---------------------------------------------------------------------------
# C header I/O
def read_c_array(path, name):
    """float16 contents of `uint16_t name[N] ... = { ... };`.  `path` may be
    a list of headers, searched in order."""
    paths = path if isinstance(path, (list, tuple)) else [path]
    for path in paths:
        if re.search(r"\b" + re.escape(name) + r"\s*\[", Path(path).read_text()):
            break
    text = Path(path).read_text()
    m = re.search(r"\b" + re.escape(name) + r"\s*\[\s*(\d+)\s*\][^=]*=\s*\{(.*?)\}",
                  text, re.S)
    if not m:
        raise SystemExit(f"{path}: no array {name}")
    values = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]+)", m.group(2))]
    if len(values) != int(m.group(1)):
        raise SystemExit(f"{path}: {name} has {len(values)} of {m.group(1)} values")
    return np.array(values, dtype=np.uint16).view(np.float16)


def read_c_define(path, name):
    m = re.search(r"#define\s+" + re.escape(name) + r"\s+(\d+)u?\b",
                  Path(path).read_text())
    if not m:
        raise SystemExit(f"{path}: no #define {name}")
    return int(m.group(1))


def write_c_array(path, guard, name, values, comment):
    bits = np.ascontiguousarray(values, dtype=np.float16).view(np.uint16).ravel()
    lines = [f"/* Generated by transformer_app.py -- {comment} */",
             f"#ifndef {guard}", f"#define {guard}", "",
             "#include <stdint.h>", "",
             f"static const uint16_t {name}[{bits.size}] "
             "__attribute__((aligned(16))) = {"]
    for i in range(0, bits.size, 8):
        lines.append("  " + ", ".join(f"0x{b:04x}" for b in bits[i:i + 8]) + ",")
    lines += ["};", "", f"#endif /* {guard} */", ""]
    Path(path).write_text("\n".join(lines))


# ---------------------------------------------------------------------------
def firmware_weights(path):
    """Layer 0 + projection of tformer_weights.h, tile layouts undone."""
    d_ff = read_c_define(path, "TF_DFF")
    tiles = d_ff // 16
    a = lambda name: read_c_array(path, name)
    w1 = a("tf_l0_w1").reshape(tiles, D, 16).transpose(1, 0, 2).reshape(D, d_ff)
    return dict(wq=a("tf_l0_wq").reshape(D, D), wk=a("tf_l0_wk").reshape(D, D),
                wv=a("tf_l0_wv").reshape(D, D), wo=a("tf_l0_wo").reshape(D, D),
                w1=np.ascontiguousarray(w1), w2=a("tf_l0_w2").reshape(d_ff, D),
                proj=a("tf_proj").reshape(F, D), pos=a("tf_pos").reshape(L, D),
                scale=1.0, post_scale=1.0)       # folded into wq / wv


def firmware_value(path, name):
    """A firmware stage value as the graph sees it ([1, 12, cols])."""
    v = read_c_array(path, name)
    if name == "tf_features":       # tile-major [2][12][16] -> [12][32]
        v = np.concatenate(list(v.reshape(F // 16, L, 16)), axis=1)
    return v.reshape(1, L, -1)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--block", choices=sorted(FIRMWARE_STAGES), default="layer")
    ap.add_argument("--d-ff", type=int, default=48,
                    help="random weights only (the firmware's is TF_DFF)")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--weights", type=Path, help="tformer_weights.h")
    ap.add_argument("--vectors", type=Path, help="tformer_vectors.h")
    ap.add_argument("--out", type=Path, required=True, help="the .onnx model")
    ap.add_argument("--header-dir", type=Path,
                    help="write tf_input.h, tf_golden.h, tensor_dim.h")
    ap.add_argument("--verify", action="store_true",
                    help="also compare with onnxruntime (loosely)")
    a = ap.parse_args()
    if bool(a.weights) != bool(a.vectors):
        ap.error("--weights and --vectors go together")

    in_cols = F if a.block in ("proj", "proj_layer") else D
    if a.weights:
        p = firmware_weights(a.weights)
        stage_in, stage_out = FIRMWARE_STAGES[a.block]
        # Stage goldens are in tformer_vectors.h (inc_l1) or, for the 2-layer
        # export of `make model`, in tformer_weights.h.
        headers = [a.vectors, a.weights]
        h = firmware_value(headers, stage_in)
        source = f"{a.weights.name} layer 0, input {stage_in}"
    else:
        p = G.make_weights(a.seed, a.d_ff)
        h = (np.random.default_rng(a.seed + 1).standard_normal((1, L, in_cols))
             .astype(np.float16))
        source = f"seed {a.seed}"
    d_ff = p["w1"].shape[1]

    model = G.build_model(a.block, p, 18)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    onnx.save(model, a.out)
    golden = G.redmule_reference(a.block, p, h)
    print(f"wrote {a.out}  block={a.block} d_ff={d_ff} ({source})")

    if a.weights:
        fw = firmware_value(headers, stage_out)
        if not np.array_equal(golden.view(np.uint16), fw.view(np.uint16)):
            diff = np.count_nonzero(golden.view(np.uint16) != fw.view(np.uint16))
            raise SystemExit(f"golden differs from the firmware's {stage_out} in "
                             f"{diff} values (weights and vectors from different "
                             "exports, or TF_STAGE_GOLDEN arrays missing?)")
        print(f"golden == firmware {stage_out}: bit-exact")

    if a.header_dir:
        a.header_dir.mkdir(parents=True, exist_ok=True)
        write_c_array(a.header_dir / "tf_input.h", "TF_INPUT_H", "tf_input", h,
                      f"graph input [{L}][{in_cols}], row-major; {source}")
        write_c_array(a.header_dir / "tf_golden.h", "TF_GOLDEN_H", "tf_golden",
                      golden, f"{a.block} output [{L}][{D}], bit-exact RedMulE "
                      f"FP16; {source}")
        (a.header_dir / "tensor_dim.h").write_text("\n".join([
            "/* Generated by transformer_app.py */", "#ifndef TENSOR_DIM_H",
            "#define TENSOR_DIM_H", "", f"#define FRAMES {L}",
            f"#define IN_COLS {in_cols}", f"#define D_MODEL {D}",
            f"#define D_FF {d_ff}", f'#define BLOCK_NAME "{a.block}"', "",
            "#endif /* TENSOR_DIM_H */", ""]))
        print(f"wrote {a.header_dir}/tf_input.h, tf_golden.h, tensor_dim.h")

    if a.verify:
        import onnxruntime as ort
        opts = ort.SessionOptions()
        opts.log_severity_level = 3
        sess = ort.InferenceSession(a.out.as_posix(), opts,
                                    providers=["CPUExecutionProvider"])
        got = sess.run(["y"], {"h": h})[0].astype(np.float64)
        ref = G.float_reference(a.block, p, h)
        print(f"onnxruntime vs float64: {np.abs(got - ref).max():.4g}, "
              f"RedMulE golden vs float64: "
              f"{np.abs(golden.astype(np.float64) - ref).max():.4g}")


if __name__ == "__main__":
    main()
