
prj_path := $(shell git rev-parse --show-toplevel)
num_cores := $(shell nproc)
num_cores_half := $(shell echo "$$(($(num_cores) / 2)"))
VLT_CXX := /usr/bin/clang++
VLT_CC  := /usr/bin/clang


INSTALL_PREFIX            ?= install
TOOLS_DIR                 ?= $(prj_path)/tools
INSTALL_DIR               ?= $(prj_path)/${INSTALL_PREFIX}
GCC_INSTALL_DIR           ?= ${INSTALL_DIR}/riscv-gcc
LLVM_INSTALL_DIR          ?= ${INSTALL_DIR}/riscv-llvm
ISA_SIM_INSTALL_DIR       ?= ${INSTALL_DIR}/riscv-isa-sim
ISA_SIM_MOD_INSTALL_DIR   ?= ${INSTALL_DIR}/riscv-isa-sim-mod
OPENOCD_INSTALL_DIR       ?= ${INSTALL_DIR}/openocd
OSS_CAD_SUITE_INSTALL_DIR ?= ${INSTALL_DIR}/oss-cad-suite
OPENROAD_INSTALL_DIR      ?= ${INSTALL_DIR}/openroad
OPENROAD_VERSION          ?= a008522d88b669ac4c985609533cf5a3d2649222
VERIL_INSTALL_DIR         ?= ${INSTALL_DIR}/verilator
VERIL_VERSION             ?= v5.036
BENDER_INSTALL_DIR        ?= ${INSTALL_DIR}/bender

all: dev-dep verilator riscv32-gcc riscv32-llvm  openocd

${TOOLS_DIR}:
	mkdir -p $@

${INSTALL_DIR}:
	mkdir -p $@

## Install Verilator
verilator: ${TOOLS_DIR} ${INSTALL_DIR} ${VERIL_INSTALL_DIR}/bin/verilator

${VERIL_INSTALL_DIR}/bin/verilator:
	rm -fr $(TOOLS_DIR)/verilator
	cd $(TOOLS_DIR) && git clone https://github.com/verilator/verilator.git
	# Checkout the right version
	cd $(TOOLS_DIR)/verilator  && git reset --hard && git fetch && git checkout ${VERIL_VERSION}
	# Compile verilator
	cd $(TOOLS_DIR)/verilator  && git clean -xfdf && autoconf && \
	./configure --prefix=$(VERIL_INSTALL_DIR) CXX=$(VLT_CXX) CC=$(VLT_CC) && make -j$(num_cores_half)  && make install
	touch ${VERIL_INSTALL_DIR}/bin/verilator



.PHONY: cores

cores:
	@num_cores=$$(nproc); \
	num_cores=$$((num_cores / 2); \
	echo "Number of cores available on this machine (divided by 2): $$num_cores"

riscv32-gcc: $(GCC_INSTALL_DIR)

$(GCC_INSTALL_DIR): vendor/riscv32-elf-gcc.url
	rm -fr $(GCC_INSTALL_DIR)
	mkdir -p $(INSTALL_DIR)
	cd $(TOOLS_DIR) && \
	wget  `cat $(CURDIR)/$<` -O riscv.tar.gz && \
	tar -xzvf riscv.tar.gz -C  $(INSTALL_DIR)/ riscv	
	mv $(INSTALL_DIR)/riscv $(GCC_INSTALL_DIR)
	touch  $(GCC_INSTALL_DIR)


riscv32-llvm: $(LLVM_INSTALL_DIR)

$(TOOLS_DIR)/riscv32-elf-llvm.tar.gz: vendor/riscv32-elf-llvm.url
	cd $(TOOLS_DIR) && \
	wget `cat $(CURDIR)/$<` -O riscv32-elf-llvm.tar.gz && \
	touch riscv32-elf-llvm.tar.gz

$(LLVM_INSTALL_DIR): $(TOOLS_DIR)/riscv32-elf-llvm.tar.gz
	rm -fr $(LLVM_INSTALL_DIR)
	mkdir -p $(INSTALL_DIR)
	cd $(TOOLS_DIR) && \
	tar -xzvf riscv32-elf-llvm.tar.gz -C  $(INSTALL_DIR)/ riscv-llvm
	touch  $(LLVM_INSTALL_DIR)


## Install development dependencies
dev-dep:
	sudo apt-get install flex bison clang help2man
	sudo apt-get install libelf-dev autoconf
	sudo apt-get install srecord gtkwave
	sudo apt-get install libyaml-cpp-dev libboost-all-dev
	sudo apt-get install gawk


ol-dev:
	sudo dnf install help2man

.PHONY: dev-dep ol-dev 

$(HOME)/eth/$(BENDER_ARCH_FILE):
	mkdir -p $(HOME)/eth && cd $(HOME)/eth       &&  \
	wget $(BENDER_DOWNLOAD_LINK)                 

.PHONY: bender
## Install Bender
bender: 
	@echo "Installing Bender..."
	mkdir -p $(BENDER_INSTALL_DIR)
	cd $(BENDER_INSTALL_DIR) &&  \
	curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh
	

$(TOOLS_DIR)/xpack-openocd.tar.gz: ${TOOLS_DIR} vendor/xpack-openocd.url
	cd $(TOOLS_DIR) && \
	wget `cat $(CURDIR)/$(word 2, $^)` -O xpack-openocd.tar.gz 
	touch $@

.PHONY: openocd
## Install OpenOCD from xpack
openocd: $(TOOLS_DIR)/xpack-openocd.tar.gz
	mkdir -p $(OPENOCD_INSTALL_DIR)
	cd $(TOOLS_DIR) && \
	tar -xzvf xpack-openocd.tar.gz  --strip-components=1 -C $(OPENOCD_INSTALL_DIR)/ 
	touch  $(OPENOCD_INSTALL_DIR)

$(TOOLS_DIR)/oss-cad-suite-linux-x64-20260109.tgz: vendor/oss-cad-suite.url
	cd $(TOOLS_DIR) && \
	wget `cat $(CURDIR)/$<` -O oss-cad-suite-linux-x64-20260109.tgz 
	touch $@

.PHONY: oss-cad-suite
## Install yosys from YosysHQ/oss-cad-suite
oss-cad-suite: $(TOOLS_DIR) $(TOOLS_DIR)/oss-cad-suite-linux-x64-20260109.tgz
	mkdir -p $(OSS_CAD_SUITE_INSTALL_DIR)
	cd $(TOOLS_DIR) && \
	tar -xzvf oss-cad-suite-linux-x64-20260109.tgz  --strip-components=1 -C $(OSS_CAD_SUITE_INSTALL_DIR)/ 
	touch  $(OSS_CAD_SUITE_INSTALL_DIR)


OPENROAD_REPO := $(TOOLS_DIR)/OpenROAD/.git

$(OPENROAD_REPO): ${TOOLS_DIR}
	cd $(TOOLS_DIR) && git clone https://github.com/The-OpenROAD-Project/OpenROAD.git

openroad-clone: $(OPENROAD_REPO)
	rm -fr $(OPENROAD_INSTALL_DIR)
	# Checkout the right version
	cd $(TOOLS_DIR)/OpenROAD  && \
	git reset --hard && \
	git fetch --all --tags && \
	git switch --detach ${OPENROAD_VERSION} && \
	git submodule update --init --recursive	&& \
	cd ./etc && . ./DependencyInstaller.sh
	


.PHONY: openroad
## Build and install OpenROAD
openroad: openroad-clone
	cd $(TOOLS_DIR)/OpenROAD   && rm -fr build && mkdir -p build 
	cd $(TOOLS_DIR)/OpenROAD/build && \
	cmake .. && \
	make -j2 && make DESTDIR=$(OPENROAD_INSTALL_DIR) install
	
include common.mk
