#!/usr/bin/env python3
"""Summarize graph.ll for main.c: inc/graph_info.h.

    GRAPH_TILES     RedMulE tiles the schedule uses (highest tile + 1)
    GRAPH_LAUNCHES  omrm_gemm_f16_16_12_16 calls (main_graph + preload)
    GRAPH_WAITS     omrm_wait calls

and prints the onnx_redmule_runtime functions graph.ll calls, so a missing
one is obvious before the link fails.  The first argument of every runtime
call (the tile) and the wait masks are literals in the emitted IR.
"""
import re
import sys
from pathlib import Path


def main():
    ll, out = Path(sys.argv[1]), Path(sys.argv[2])
    text = ll.read_text()
    tiles = {int(t) for t in re.findall(
        r"call void @omrm_gemm_f16_16_12_16\(i32 (\d+)", text)}
    for mask in re.findall(r"call void @omrm_wait\(i32 (\d+)\)", text):
        tiles |= {b for b in range(32) if int(mask) >> b & 1}
    launches = len(re.findall(r"call void @omrm_gemm_f16_16_12_16\(", text))
    waits = len(re.findall(r"call void @omrm_wait\(", text))
    ids = sorted({int(i) for i in re.findall(
        r"call ptr @_reserveMemory\(i32 (\d+)\)", text)})
    runtime = sorted(set(re.findall(r"^declare [^@]*@(omrm_\w+)\(", text, re.M)))

    n_tiles = max(tiles) + 1 if tiles else 1
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join([
        f"/* Generated by graph_info.py from {ll.name} */",
        "#ifndef GRAPH_INFO_H", "#define GRAPH_INFO_H", "",
        f"#define GRAPH_TILES {n_tiles}u",
        f"#define GRAPH_LAUNCHES {launches}u",
        f"#define GRAPH_WAITS {waits}u",
        f"#define GRAPH_ALLOC_IDS {len(ids)}u", "",
        "#endif /* GRAPH_INFO_H */", ""]))
    print(f"{ll.name}: {launches} launches, {waits} waits on {n_tiles} "
          f"tile(s); _reserveMemory ids {ids}")
    print("  runtime: " + ", ".join(runtime))
    if ids != [1]:
        sys.exit(f"{ll.name}: main.c expects exactly one allocation, id 1 "
                 f"(the result); got {ids}")


if __name__ == "__main__":
    main()
