#!/usr/bin/env python3
"""Model and firmware headers for isolde/sw/onnx_radar_attention.

From one radar_attention export (the inc/ that `make model` writes there:
tformer_weights.h + tformer_vectors.h) this writes

    models/tformer_encoder.onnx   the whole encoder as ONNX (tformer_onnx.py,
                                  a copy of onnx-mlir's
                                  test-isolde/attention/models/tformer_onnx.py)
    inc/tformer_config.h          the export's #defines (TF_FRAMES ..
                                  TF_WEIGHTS_ID, TF_GOLDEN_CASE_ID), without
                                  the weight arrays: onnx-mlir compiles those
                                  into graph.ll
    inc/tformer_vectors.h         copied unchanged: tf_features,
                                  tf_logits_golden, tf_class_name, the case id

so main.c prints exactly what radar_attention prints, for the same case and
the same weights, and `make cases` images fit both builds.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import onnx

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import tformer_onnx  # noqa: E402

REQUIRED = ('TF_FRAMES', 'TF_FEATURES', 'TF_DMODEL', 'TF_DFF', 'TF_LAYERS',
            'TF_CLASSES', 'TF_WEIGHTS_ID', 'TF_GOLDEN_CASE_ID')


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument('--radar-inc', type=Path, required=True,
                    help='radar_attention/inc (tformer_weights.h, '
                         'tformer_vectors.h)')
    ap.add_argument('--weights-name', default='tformer_weights.h')
    ap.add_argument('--out', type=Path, required=True, help='the .onnx model')
    ap.add_argument('--header-dir', type=Path, required=True)
    a = ap.parse_args()

    weights = a.radar_inc / a.weights_name
    vectors = a.radar_inc / 'tformer_vectors.h'
    for path in (weights, vectors):
        if not path.exists():
            raise SystemExit(f'{path} not found: run `make model` in '
                             'isolde/sw/radar_attention first')

    text = weights.read_text()
    defines = re.findall(r'^#define (TF_\w+) (.+)$', text, re.M)
    names = {name for name, _ in defines}
    missing = [n for n in REQUIRED if n not in names]
    if missing:
        raise SystemExit(f'{weights}: no {", ".join(missing)} (an export from '
                         'an older tformer.py? re-run make model)')
    vec_case = re.search(r'#define TF_CASE_ID "(\w+)"', vectors.read_text())
    golden_case = dict(defines)['TF_GOLDEN_CASE_ID'].strip('"')
    if not vec_case or vec_case.group(1) != golden_case:
        raise SystemExit(f'{vectors.name} (case {vec_case and vec_case.group(1)})'
                         f' and {weights.name} (goldens for case {golden_case})'
                         ' come from different exports; re-run make model')

    params = tformer_onnx.params_from_header(weights)
    model = tformer_onnx.build_model(params)
    tformer_onnx.check(model)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    onnx.save(model, a.out)

    a.header_dir.mkdir(parents=True, exist_ok=True)
    keep = [d for d in defines if d[0] not in ('TF_STAGE_GOLDEN',)]
    # tf_logits_golden (the case's reference logits) is in the weights header
    # of current exports, in the vectors header of older ones.
    golden = []
    if not re.search(r'\btf_logits_golden\s*\[', vectors.read_text()):
        m = re.search(r'^static const uint16_t tf_logits_golden\[.*?\};$',
                      text, re.M | re.S)
        if not m:
            raise SystemExit(f'no tf_logits_golden in {weights} or {vectors}')
        golden = ['', m.group(0)]
    (a.header_dir / 'tformer_config.h').write_text('\n'.join(
        [f'/* Generated by onnx_radar_model.py from {weights.name}: its',
         ' * defines and tf_logits_golden; the weights are compiled into',
         ' * graph.ll. */',
         '#ifndef TFORMER_CONFIG_H', '#define TFORMER_CONFIG_H', '',
         '#include <stdint.h>', '']
        + [f'#define {n} {v}' for n, v in keep] + golden
        + ['', '#endif /* TFORMER_CONFIG_H */', '']))
    shutil.copyfile(vectors, a.header_dir / 'tformer_vectors.h')

    weights_id = dict(defines)['TF_WEIGHTS_ID'].strip('"')
    print(f'wrote {a.out}: {len(params["layers"])} layer(s), weights '
          f'{weights_id}, case {golden_case}')
    print(f'wrote {a.header_dir}/tformer_config.h, tformer_vectors.h')


if __name__ == '__main__':
    main()
