set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED RISCV_LLVM_ROOT)
  if(DEFINED ENV{RISCV_LLVM_ROOT})
    set(RISCV_LLVM_ROOT "$ENV{RISCV_LLVM_ROOT}")
  else()
    message(FATAL_ERROR
      "Set RISCV_LLVM_ROOT to the RISC-V LLVM installation directory")
  endif()
endif()

find_program(CMAKE_C_COMPILER clang
  PATHS "${RISCV_LLVM_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
find_program(CMAKE_OBJCOPY llvm-objcopy
  PATHS "${RISCV_LLVM_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_OBJDUMP llvm-objdump
  PATHS "${RISCV_LLVM_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)

set(CMAKE_C_COMPILER_TARGET riscv32-unknown-elf)
set(CMAKE_ASM_COMPILER_TARGET riscv32-unknown-elf)

