#!/usr/bin/env python3
"""
verilator_flist_to_slang.py

Convert a Verilator-style command file (.f / flist) into command files for
multiple EDA tools. Options and sources are deduplicated (first-seen order).

Output selectors (any combination):
  -o     / --output          Full slang flist  (+incdir+ / -D / -G + sources)
  -ops   / --options-file     slang options-only flist (+incdir+ / -D / -G)
  -veri  / --verilator-opts   Verilator options-only  (+incdir+ / +define+ / -G<n>=<v>)
  -questa/ --questa-opts       Questa   options-only  (+incdir+ / +define+)

Parameter overrides (-G):
  slang    : spaced form  '-G NAME=VALUE'   (accepted by slang)
  Verilator: attached form '-GNAME=VALUE'   (required; spaced form is
             mis-tokenized by Verilator's -f command-file parser as a bare
             source/module name)
  Questa   : NOT supported in vlog command files. Apply at vopt/vsim via
             -g NAME=VALUE. Emitted as commented hints + a warning.
"""

import argparse
import shlex
import sys
from pathlib import Path

DROP_EXTENSIONS = {".vlt", ".c", ".cc", ".cpp", ".cxx", ".h", ".hpp"}


def convert(tokens):
    incdirs, defines, params, sources = [], [], [], []
    dropped, unrecognized = [], []
    seen_incdirs, seen_defines, seen_params, seen_sources = set(), set(), set(), set()

    i, n = 0, len(tokens)
    while i < n:
        tok = tokens[i]

        if tok.startswith("+incdir+"):
            path = tok[len("+incdir+"):]
            if path and path not in seen_incdirs:
                seen_incdirs.add(path)
                incdirs.append(path)
            i += 1

        elif tok == "-CFLAGS":
            arg = tokens[i + 1] if i + 1 < n else ""
            dropped.append(f"-CFLAGS {arg}".strip())
            i += 2 if i + 1 < n else 1

        elif tok.startswith("+define+"):
            define = tok[len("+define+"):]
            if define and define not in seen_defines:
                seen_defines.add(define)
                defines.append(define)
            i += 1

        elif tok.startswith("-G"):
            rest = tok[2:]
            if not rest and i + 1 < n:
                rest = tokens[i + 1]
                i += 1
            if rest and rest not in seen_params:
                seen_params.add(rest)
                params.append(rest)
            i += 1

        elif tok.startswith("-D"):
            rest = tok[2:]
            if not rest and i + 1 < n:
                rest = tokens[i + 1]
                i += 1
            if rest and rest not in seen_defines:
                seen_defines.add(rest)
                defines.append(rest)
            i += 1

        elif tok.startswith("-") or tok.startswith("+"):
            unrecognized.append(tok)
            i += 1

        else:
            ext = Path(tok).suffix.lower()
            if ext in DROP_EXTENSIONS:
                dropped.append(tok)
            else:
                if tok not in seen_sources:
                    seen_sources.add(tok)
                    sources.append(tok)
            i += 1

    return incdirs, defines, params, sources, dropped, unrecognized


def format_slang(incdirs, defines, params, sources, options_only=False):
    header = "(options only)" if options_only else ""
    lines = [
        f"# Auto-generated by flist2slang.py (slang format) {header}".rstrip(),
        "# Usage: slang -f <this file>",
        "",
    ]
    if incdirs:
        lines.append("# Include directories")
        lines += [f"+incdir+{d}" for d in incdirs]
        lines.append("")
    if defines:
        lines.append("# Preprocessor defines")
        lines += [f"-D {d}" for d in defines]
        lines.append("")
    if params:
        lines.append("# Top-level parameter overrides")
        lines += [f"-G {p}" for p in params]
        lines.append("")
    if not options_only and sources:
        lines.append("# Source files")
        lines += sources
        lines.append("")
    return "\n".join(lines)


def format_verilator(incdirs, defines, params):
    lines = [
        "# Auto-generated by flist2slang.py (Verilator options)",
        "# Usage: verilator -f <this file> ...",
        "",
    ]
    if incdirs:
        lines.append("# Include directories")
        lines += [f"+incdir+{d}" for d in incdirs]
        lines.append("")
    if defines:
        lines.append("# Preprocessor defines")
        lines += [f"+define+{d}" for d in defines]
        lines.append("")
    if params:
        lines.append("# Top-level parameter overrides (Verilator: attached -G<name>=<val> form)")
        lines += [f"-G{p}" for p in params]
        lines.append("")
    return "\n".join(lines)


def format_questa(incdirs, defines, params):
    """Returns (text, warnings_list)."""
    warnings = []
    lines = [
        "# Auto-generated by flist2slang.py (Questa vlog options)",
        "# Usage: vlog -f <this file> ...",
        "",
    ]
    if incdirs:
        lines.append("# Include directories")
        lines += [f"+incdir+{d}" for d in incdirs]
        lines.append("")
    if defines:
        lines.append("# Preprocessor defines")
        lines += [f"+define+{d}" for d in defines]
        lines.append("")
    if params:
        warnings.append(
            "parameter overrides (-G) are NOT supported by Questa vlog command "
            "files. Apply them at elaboration/sim time via vopt/vsim -g NAME=VALUE. "
            "They are written below as comments only."
        )
        lines.append("# Top-level parameter overrides")
        lines.append("# WARNING: -G is NOT understood by Questa vlog.")
        lines.append("#          Apply these to vopt/vsim as: -g NAME=VALUE")
        for p in params:
            lines.append(f"#   -g {p}")
        lines.append("")
    return "\n".join(lines), warnings


def main():
    ap = argparse.ArgumentParser(
        description="Convert a Verilator-style .f/flist into slang, Verilator "
                    "and/or Questa command files."
    )
    ap.add_argument("input", help="Path to the Verilator flist to convert")
    ap.add_argument("-o", "--output",
                    help="Full slang flist (default: stdout if no selector given)")
    ap.add_argument("-ops", "--options-file",
                    help="slang options-only flist (+incdir+/-D/-G)")
    ap.add_argument("-veri", "--verilator-opts",
                    help="Verilator options-only file (+incdir+/+define+/-G<name>=<val>)")
    ap.add_argument("-questa", "--questa-opts",
                    help="Questa vlog options-only file (+incdir+/+define+; "
                         "-G unsupported, emitted as comments + warning)")
    args = ap.parse_args()

    text = Path(args.input).read_text()
    tokens = shlex.split(text, comments=True)

    incdirs, defines, params, sources, dropped, unrecognized = convert(tokens)

    any_selector = any([args.output, args.options_file,
                        args.verilator_opts, args.questa_opts])

    if args.output:
        Path(args.output).write_text(
            format_slang(incdirs, defines, params, sources) + "\n")
        print(f"Wrote {args.output} (slang full flist)", file=sys.stderr)
    elif not any_selector:
        print(format_slang(incdirs, defines, params, sources))

    if args.options_file:
        Path(args.options_file).write_text(
            format_slang(incdirs, defines, params, sources, options_only=True) + "\n")
        print(f"Wrote {args.options_file} (slang options only)", file=sys.stderr)

    if args.verilator_opts:
        Path(args.verilator_opts).write_text(
            format_verilator(incdirs, defines, params) + "\n")
        print(f"Wrote {args.verilator_opts} (Verilator options)", file=sys.stderr)

    if args.questa_opts:
        q_text, q_warnings = format_questa(incdirs, defines, params)
        Path(args.questa_opts).write_text(q_text + "\n")
        print(f"Wrote {args.questa_opts} (Questa options)", file=sys.stderr)
        for w in q_warnings:
            print(f"WARNING: {w}", file=sys.stderr)

    print(
        f"\n{len(incdirs)} incdirs, {len(defines)} defines, "
        f"{len(params)} param overrides, {len(sources)} source files kept.",
        file=sys.stderr,
    )
    if dropped:
        print(f"{len(dropped)} Verilator-only entries dropped:", file=sys.stderr)
        for d in dropped:
            print(f"  - {d}", file=sys.stderr)
    if unrecognized:
        print(f"\n{len(unrecognized)} UNRECOGNIZED token(s):", file=sys.stderr)
        for u in unrecognized:
            print(f"  - {u}", file=sys.stderr)


if __name__ == "__main__":
    main()
