#!/usr/bin/env python3
"""
verilator_flist_to_slang.py

Convert a Verilator-style command file (.f / flist) into a command file
that slang can consume via -f.

Adds -ops/--options-file to write an options-only flist
(+incdir+, -D, -G) with no source files. All option categories
(incdirs, defines, params, sources) are deduplicated, first-seen order.
"""

import argparse
import shlex
import sys
from pathlib import Path

DROP_EXTENSIONS = {".vlt", ".c", ".cc", ".cpp", ".cxx", ".h", ".hpp"}


def convert(tokens):
    incdirs, defines, params, sources = [], [], [], []
    dropped, unrecognized = [], []
    seen_incdirs, seen_defines, seen_params, seen_sources = set(), set(), set(), set()

    i, n = 0, len(tokens)
    while i < n:
        tok = tokens[i]

        if tok.startswith("+incdir+"):
            path = tok[len("+incdir+"):]
            if path and path not in seen_incdirs:
                seen_incdirs.add(path)
                incdirs.append(path)
            i += 1

        elif tok == "-CFLAGS":
            arg = tokens[i + 1] if i + 1 < n else ""
            dropped.append(f"-CFLAGS {arg}".strip())
            i += 2 if i + 1 < n else 1

        elif tok.startswith("+define+"):
            define = tok[len("+define+"):]
            if define and define not in seen_defines:
                seen_defines.add(define)
                defines.append(define)
            i += 1

        elif tok.startswith("-G"):
            rest = tok[2:]
            if not rest and i + 1 < n:
                rest = tokens[i + 1]
                i += 1
            if rest and rest not in seen_params:
                seen_params.add(rest)
                params.append(rest)
            i += 1

        elif tok.startswith("-D"):
            rest = tok[2:]
            if not rest and i + 1 < n:
                rest = tokens[i + 1]
                i += 1
            if rest and rest not in seen_defines:
                seen_defines.add(rest)
                defines.append(rest)
            i += 1

        elif tok.startswith("-") or tok.startswith("+"):
            unrecognized.append(tok)
            i += 1

        else:
            ext = Path(tok).suffix.lower()
            if ext in DROP_EXTENSIONS:
                dropped.append(tok)
            else:
                if tok not in seen_sources:
                    seen_sources.add(tok)
                    sources.append(tok)
            i += 1

    return incdirs, defines, params, sources, dropped, unrecognized


def format_output(incdirs, defines, params, sources, options_only=False):
    if options_only:
        lines = [
            "# Auto-generated by verilator_flist_to_slang.py (options only)",
            "# Usage: slang -f <this file>",
            "",
        ]
    else:
        lines = [
            "# Auto-generated by verilator_flist_to_slang.py",
            "# Usage: slang -f <this file>",
            "",
        ]
    if incdirs:
        lines.append("# Include directories")
        lines += [f"+incdir+{d}" for d in incdirs]
        lines.append("")
    if defines:
        lines.append("# Preprocessor defines")
        lines += [f"-D {d}" for d in defines]
        lines.append("")
    if params:
        lines.append("# Top-level parameter overrides")
        lines += [f"-G {p}" for p in params]
        lines.append("")
    if not options_only and sources:
        lines.append("# Source files")
        lines += sources
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(
        description="Convert a Verilator-style .f/flist file into a slang -f command file."
    )
    ap.add_argument("input", help="Path to the Verilator flist to convert")
    ap.add_argument("-o", "--output", help="Path to write the slang flist to (default: stdout)")
    ap.add_argument(
        "-ops", "--options-file",
        help="Path to write an options-only flist (+incdir+/-D/-G, no sources)",
    )
    args = ap.parse_args()

    text = Path(args.input).read_text()
    tokens = shlex.split(text, comments=True)

    incdirs, defines, params, sources, dropped, unrecognized = convert(tokens)
    output = format_output(incdirs, defines, params, sources)

    if args.output:
        Path(args.output).write_text(output + "\n")
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        print(output)

    if args.options_file:
        opts_output = format_output(incdirs, defines, params, sources, options_only=True)
        Path(args.options_file).write_text(opts_output + "\n")
        print(f"Wrote {args.options_file} (options only)", file=sys.stderr)

    print(
        f"\n{len(incdirs)} incdirs, {len(defines)} defines, "
        f"{len(params)} param overrides, {len(sources)} source files kept.",
        file=sys.stderr,
    )
    if dropped:
        print(f"{len(dropped)} Verilator-only entries dropped:", file=sys.stderr)
        for d in dropped:
            print(f"  - {d}", file=sys.stderr)
    if unrecognized:
        print(f"\n{len(unrecognized)} UNRECOGNIZED token(s):", file=sys.stderr)
        for u in unrecognized:
            print(f"  - {u}", file=sys.stderr)


if __name__ == "__main__":
    main()
