#!/usr/bin/env python3
"""
Generate a Vivado Tcl source manifest from Slang dependency extraction.

The source list is taken from a Slang --Mmodule dependency file generated with
--depfile-sort / --depfile-trim. Slang's default dependency-file format places
one source file on each line.

Include directories and preprocessor defines are collected from one or more
Slang command files.

Top-level parameter overrides (-G) are intentionally ignored. In this flow the
FuseSoC -G parameters describe ibex_top, while Slang dependency extraction is
rooted at the outer FPGA wrapper (normally xilinx_aida).

For compatibility with the existing isolde/system/fpga/tcl/create_project.tcl,
the generated Tcl exports:

    ibex_include_dirs
    ibex_verilog_defines

and adds the trimmed source list to the current Vivado fileset.
"""

from __future__ import annotations

import argparse
import shlex
from pathlib import Path
from typing import Iterable


def append_unique(items: list[str], seen: set[str], value: str) -> None:
    if value and value not in seen:
        seen.add(value)
        items.append(value)


def tcl_quote(value: str) -> str:
    """Quote one Tcl list element using double-quoted Tcl syntax."""
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("$", "\\$")
    value = value.replace("[", "\\[")
    value = value.replace("]", "\\]")
    return f'"{value}"'


def read_dependency_sources(path: Path) -> list[str]:
    """
    Read Slang's default dependency-file format.

    --Mmodule without --depfile-target emits one source filename per line.
    Keep that ordering because --depfile-sort already made it topological.
    """
    sources: list[str] = []
    seen: set[str] = set()

    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        # Slang normally writes a raw filename. If it quoted the filename,
        # shlex removes the quotes while still preserving the single item.
        try:
            tokens = shlex.split(line, comments=False)
        except ValueError:
            tokens = []

        source = tokens[0] if len(tokens) == 1 else line
        if source.startswith(("-", "+")):
            continue

        append_unique(sources, seen, source)

    return sources


def read_slang_options(paths: Iterable[Path]) -> tuple[list[str], list[str]]:
    """Collect +incdir+ and -D options; ignore -G and all source tokens."""
    incdirs: list[str] = []
    defines: list[str] = []
    seen_incdirs: set[str] = set()
    seen_defines: set[str] = set()

    for path in paths:
        tokens = shlex.split(path.read_text(), comments=True)
        i = 0

        while i < len(tokens):
            token = tokens[i]

            if token.startswith("+incdir+"):
                append_unique(
                    incdirs,
                    seen_incdirs,
                    token[len("+incdir+"):],
                )
                i += 1
                continue

            if token == "-D":
                if i + 1 >= len(tokens):
                    raise ValueError(f"{path}: '-D' without an argument")
                append_unique(defines, seen_defines, tokens[i + 1])
                i += 2
                continue

            if token.startswith("-D") and len(token) > 2:
                append_unique(defines, seen_defines, token[2:])
                i += 1
                continue

            # Deliberately discard top-level parameter overrides.
            if token == "-G":
                if i + 1 >= len(tokens):
                    raise ValueError(f"{path}: '-G' without an argument")
                i += 2
                continue

            if token.startswith("-G"):
                i += 1
                continue

            i += 1

    return incdirs, defines


def write_tcl_list(handle, name: str, values: list[str]) -> None:
    handle.write(f"set {name} [list")
    if values:
        handle.write(" \\\n")
        for value in values:
            handle.write(f"    {tcl_quote(value)} \\\n")
    handle.write("]\n\n")


def write_vivado_tcl(
    output: Path,
    sources: list[str],
    incdirs: list[str],
    defines: list[str],
) -> None:
    with output.open("w") as handle:
        handle.write("# Auto-generated by util/slang_deps_to_vivado.py\n")
        handle.write("# Do not edit.\n\n")

        # Compatibility with the current create_project.tcl.
        write_tcl_list(handle, "ibex_include_dirs", incdirs)
        write_tcl_list(handle, "ibex_verilog_defines", defines)

        handle.write("add_files -norecurse -fileset [current_fileset] [list")
        if sources:
            handle.write(" \\\n")
            for source in sources:
                handle.write(f"    {tcl_quote(source)} \\\n")
        handle.write("]\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate Vivado Tcl from a Slang-trimmed dependency file "
            "plus Slang preprocessing options."
        )
    )
    parser.add_argument(
        "--deps",
        required=True,
        type=Path,
        help="Slang --Mmodule dependency file",
    )
    parser.add_argument(
        "--options",
        required=True,
        nargs="+",
        type=Path,
        help="Slang command files supplying +incdir+ and -D options",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Output Vivado Tcl file",
    )
    args = parser.parse_args()

    sources = read_dependency_sources(args.deps)
    incdirs, defines = read_slang_options(args.options)

    if not sources:
        raise SystemExit(f"ERROR: {args.deps} contains no source files")

    write_vivado_tcl(args.output, sources, incdirs, defines)

    print(
        f"Wrote {args.output}: "
        f"{len(sources)} sources, "
        f"{len(incdirs)} include directories, "
        f"{len(defines)} defines"
    )


if __name__ == "__main__":
    main()
