// Generated by VIO - September 25, 2026

/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Bare-metal functional test for tiled graph.ll
 */

#include <stddef.h>
#include <bsp/omp_redmule.h>
#include <bsp/fp16_utils.h>

#include "ar_input.h"
#include "br_input.h"
#include "cr_golden.h"
#include "tensor_dim.h"

#define HW_MAX_M 12
#define TILE_A_ELEMENTS (HW_MAX_M * N_SIZE)
#define TILE_C_ELEMENTS (HW_MAX_M * K_SIZE)

typedef struct {
  fp16_storage_t *cr_0;
  fp16_storage_t *ci_0;
  fp16_storage_t *cr_1;
  fp16_storage_t *ci_1;
} graph_outputs_t;

/* Bare-pointer ABI: main_graph(br, ar_0, ar_1) */
extern graph_outputs_t main_graph(const void *br, const void *ar_0,
                                  const void *ar_1);

static fp16_storage_t graph_cr_0[TILE_C_ELEMENTS] __attribute__((aligned(16)));
static fp16_storage_t graph_ci_0[TILE_C_ELEMENTS] __attribute__((aligned(16)));
static fp16_storage_t graph_cr_1[TILE_C_ELEMENTS] __attribute__((aligned(16)));
static fp16_storage_t graph_ci_1[TILE_C_ELEMENTS] __attribute__((aligned(16)));

void *_reserveMemory(int32_t id) {
  if (id == 1) return graph_cr_0;
  if (id == 2) return graph_ci_0;
  if (id == 3) return graph_cr_1;
  if (id == 4) return graph_ci_1;

  printf("[ONNX-GEMM] unexpected allocation id=%d\n", (int)id);
  _Exit(0x0bad1000);
  return NULL;
}

int main(int argc, char **argv) {
  graph_outputs_t outputs;
  uint32_t errors = 0u;
  uint32_t worst_ulp = 0u;

  (void)argc;
  (void)argv;

  printf("[ONNX-GEMM] graph.ll bare-metal test\n");
  printf("[ONNX-GEMM] A=%dx%d (2 tiles), B=%dx%d, C=%dx%d FP16\n",
         M_SIZE, N_SIZE, N_SIZE, K_SIZE, M_SIZE, K_SIZE);

  if (isolde_get_tile_cnt() < 2u) {
    printf("[ONNX-GEMM] ERROR: at least two RedMulE tiles are required\n");
    return 1;
  }

  const void *ar_0_ptr = (const void *)ar_inp;
  const void *ar_1_ptr = (const void *)(ar_inp + TILE_A_ELEMENTS);

  const fp16_storage_t *cr_golden_0_ptr = cr_golden;
  const fp16_storage_t *cr_golden_1_ptr = cr_golden + TILE_C_ELEMENTS;

  START_PERFCNT(0x1)
  isolde_clear_tile_ip((uint32_t)-1);
  outputs = main_graph((const void *)br_inp, ar_0_ptr, ar_1_ptr);
  STOP_PERFCNT(0x1)
  printPerfCnt();

  errors += validate_result(outputs.cr_0,
      (const _Float16 *)cr_golden_0_ptr,
      TILE_C_ELEMENTS, K_SIZE, "Cr_0", &worst_ulp);

  errors += validate_result(outputs.cr_1,
      (const _Float16 *)cr_golden_1_ptr,
      TILE_C_ELEMENTS, K_SIZE, "Cr_1", &worst_ulp);

  printf("[ONNX-GEMM] errors=%d worst_ulp=%d allowed_ulp=%d\n",
         (unsigned)errors, (unsigned)worst_ulp, (unsigned)MAX_ULP_ERROR);

  if (errors != 0u) {
    printf("[ONNX-GEMM] FAILED\n");
    return 1;
  }

  printf("[ONNX-GEMM] PASSED\n");
  return 0;
}
