ROOT_DIR            :=  $(shell git rev-parse --show-toplevel)
mkfile_path         := $(shell git rev-parse --show-toplevel)/isolde/system
IBEX_CONFIG         ?=  isolde
FUSESOC_CONFIG_OPTS ?= 
FUSESOC_PARAMS      ?=
TEST                ?= dhrystone
TEST_SRC_DIR	    = $(ROOT_DIR)/isolde/sw/$(TEST)
TEST_BIN_DIR	    = $(mkfile_path)/sw/bin
test-program        ?= $(TEST_BIN_DIR)/$(TEST)
BUILD_DIR           := build/$(IBEX_CONFIG)
SYNTH_DIR           := synth/$(IBEX_CONFIG)
TMP_DIR             := tmp/$(IBEX_CONFIG)
FUSESOC_BUILD_ROOT  := $(mkfile_path)/$(TMP_DIR)
FUSESOC_SYNTH_ROOT  ?= $(mkfile_path)/$(SYNTH_DIR)
BENDER_RTL_ROOT     ?= $(mkfile_path)
BENDER_SYNTH_TARGET ?= 
BENDER_EXTRA_TARGET ?= -t aida_mmio
FUSESOC_PROJECT     := isolde
FUSESOC_CORE        := ibex
FUSESOC_SYSTEM      := lca_dm_system
FUSESOC_PKG_NAME    := $(FUSESOC_PROJECT):$(FUSESOC_CORE):$(FUSESOC_SYSTEM)
