#!/usr/bin/env python3
"""Synthetic receive beamforming, FP16 vectors, ONNX export and RTL plots.

The input is a synthetic range-processed antenna cube (one snapshot), not
raw ADC data. The accelerated operation is C = A @ B in split-complex form.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

import numpy as np

M, N, K, BLOCK_M = 36, 16, 16, 12
ANGLES = np.linspace(-70.0, 70.0, M)
RANGES = 25.0 * (1 + np.arange(K))
TARGETS = ((-30.0, 4, 1.0, 0.3), (6.0, 8, 0.8, 1.1),
           (38.0, 12, 0.65, -0.7))
ABS_TOL = 2.0**-12
ULP_TOL = 4


def make_scene(seed=7):
    """Broadside is 0 degrees; a(theta)[n] = exp(+j*pi*n*sin(theta))."""
    antenna = np.arange(N)
    a = np.exp(-1j * np.pi * np.sin(np.deg2rad(ANGLES))[:, None]
               * antenna[None, :]) / N  # conjugate steering / N
    b = np.zeros((N, K), dtype=np.complex128)
    bins = np.arange(K)
    for angle, range_bin, amplitude, phase in TARGETS:
        steering = np.exp(1j * np.pi * antenna * np.sin(np.deg2rad(angle)))
        profile = np.exp(-0.5 * ((bins - range_bin) / 0.48)**2)
        echo = amplitude * profile * np.exp(1j * (phase + 0.13 * bins))
        b += steering[:, None] * echo[None, :]
    rng = np.random.default_rng(seed)
    b += 0.02 / np.sqrt(2) * (rng.standard_normal(b.shape)
                            + 1j * rng.standard_normal(b.shape))
    return a, b


def real_accumulate(x, w, y=None):
    """Match isolde/sw/scripts/complex_gemm/complex_gemm.py's reference.

    Float32 product/add followed by FP16 rounding after each reduction step.
    This is a software arithmetic model, not a cycle-accurate RTL simulator.
    """
    x, w = np.asarray(x, dtype=np.float16), np.asarray(w, dtype=np.float16)
    out = (np.zeros((x.shape[0], w.shape[1]), dtype=np.float16)
           if y is None else np.array(y, dtype=np.float16, copy=True))
    for n in range(x.shape[1]):
        out = (x[:, n, None].astype(np.float32)
               * w[None, n, :].astype(np.float32)
               + out.astype(np.float32)).astype(np.float16)
    return out


def fp16_reference(ar, ai, br, bi):
    cr = real_accumulate(ai, -bi, real_accumulate(ar, br))
    ci = real_accumulate(ai, br, real_accumulate(ar, bi))
    return cr, ci


def prepare(seed=7):
    a, b = make_scene(seed)
    ar, ai, br, bi = (np.ascontiguousarray(x, dtype=np.float16)
                      for x in (a.real, a.imag, b.real, b.imag))
    cr, ci = fp16_reference(ar, ai, br, bi)
    quantized = ((ar.astype(float) + 1j * ai.astype(float))
                 @ (br.astype(float) + 1j * bi.astype(float)))
    case_id = hashlib.sha256(b''.join(x.astype('<f2').tobytes()
                            for x in (ar, ai, br, bi))).hexdigest()[:16]
    return dict(ar=ar, ai=ai, br=br, bi=bi, cr=cr, ci=ci,
                ideal=a @ b, quantized=quantized, seed=seed, case_id=case_id)


def emit_header(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ['/* Generated by beamforming.py; IEEE binary16 raw storage. */',
             '#ifndef RADAR_VECTORS_H', '#define RADAR_VECTORS_H',
             '#include <stdint.h>', f'#define BF_M {M}u',
             f'#define BF_N {N}u', f'#define BF_K {K}u',
             f'#define BF_BLOCK_M {BLOCK_M}u',
             f'#define BF_CASE_ID "{data["case_id"]}"',
             f'#define BF_SEED {data["seed"]}u']
    for key in ('ar', 'ai', 'br', 'bi', 'cr', 'ci'):
        values = data[key].view(np.uint16).ravel()
        name = 'bf_' + key + ('_golden' if key in ('cr', 'ci') else '')
        lines.append(f'static const uint16_t {name}[{len(values)}] '
                     '__attribute__((aligned(16))) = {')
        lines.extend('  ' + ', '.join(f'0x{int(v):04x}' for v in values[i:i+8])
                     + ',' for i in range(0, len(values), 8))
        lines.append('};')
    lines += ['#endif', '']
    path.write_text('\n'.join(lines))


def export_onnx(folder, data):
    import onnx
    from onnx import TensorProto as T, helper as h
    from onnx.reference import ReferenceEvaluator

    folder.mkdir(parents=True, exist_ok=True)
    shapes = ((BLOCK_M, N), (BLOCK_M, N), (N, K), (N, K))
    names = ('Ar', 'Ai', 'Br', 'Bi')
    def values(dtype):
        return [h.make_tensor_value_info(n, dtype, list(s))
                for n, s in zip(names, shapes)]
    def outputs(dtype):
        return [h.make_tensor_value_info(n, dtype, [BLOCK_M, K])
                for n in ('Cr', 'Ci')]

    custom = h.make_model(h.make_graph([
        h.make_node('RedMulEComplexGemm', list(names), ['Cr', 'Ci'],
                    domain='com.isolde', name='radar_complex_gemm')],
        'radar_block', values(T.FLOAT16), outputs(T.FLOAT16)),
        producer_name='ISOLDE radar beamforming', ir_version=8,
        opset_imports=[h.make_opsetid('', 18), h.make_opsetid('com.isolde', 1)])
    # Structural check only: ONNX does not know the vendor operator semantics.
    onnx.checker.check_model(custom)
    onnx.save(custom, folder / 'radar_block_f16.onnx')

    nodes = [h.make_node('MatMul', [l, r], [o]) for l, r, o in
             [('Ar', 'Br', 'rr'), ('Ai', 'Bi', 'ii'),
              ('Ar', 'Bi', 'ri'), ('Ai', 'Br', 'ir')]]
    nodes += [h.make_node('Sub', ['rr', 'ii'], ['Cr']),
              h.make_node('Add', ['ri', 'ir'], ['Ci'])]
    portable = h.make_model(h.make_graph(nodes, 'radar_portable_f32',
                            values(T.FLOAT), outputs(T.FLOAT)),
                            ir_version=8, opset_imports=[h.make_opsetid('', 18)])
    onnx.checker.check_model(portable)
    evaluator = ReferenceEvaluator(portable)
    max_error = 0.0
    for start in range(0, M, BLOCK_M):
        inputs = {name: data[name.lower()][start:start+BLOCK_M].astype(np.float32)
                  if name.startswith('A') else data[name.lower()].astype(np.float32)
                  for name in names}
        real, imag = evaluator.run(None, inputs)
        expected = data['quantized'][start:start+BLOCK_M]
        error = float(np.max(np.abs(real + 1j * imag - expected)))
        max_error = max(max_error, error)
        np.testing.assert_allclose(real + 1j * imag, expected, rtol=2e-5, atol=2e-7)
    onnx.save(portable, folder / 'radar_block_portable_f32.onnx')
    return {'portable_onnx_max_complex_error': max_error,
            'custom_onnx': 'structurally checked; requires ISOLDE ONNX-MLIR'}


def ordered(bits):
    bits = np.asarray(bits, dtype=np.uint16).astype(np.int32)
    return np.where(bits & 0x8000, 0x8000 - (bits & 0x7fff), 0x8000 + bits)


def compare(actual_r, actual_i, data):
    result = {}
    failed = 0
    for key, actual in (('cr', actual_r), ('ci', actual_i)):
        expected = data[key]
        actual = np.asarray(actual, dtype=np.float16)
        ulp = np.abs(ordered(actual.view(np.uint16))
                     - ordered(expected.view(np.uint16)))
        delta = np.abs(actual.astype(float) - expected.astype(float))
        bad = ~np.isfinite(actual) | ((ulp > ULP_TOL) & (delta > ABS_TOL))
        failed += int(bad.sum())
        result[key] = dict(errors=int(bad.sum()), worst_ulp=int(ulp.max()),
                           max_abs_error=float(delta.max()))
    result['errors'] = failed
    return result


def parse_log(path, case_id):
    text = path.read_text(errors='replace')
    meta = re.findall(r'\[RADAR\] case=([0-9a-f]+) mode=(\w+) rows=(\d+) cols=(\d+)', text)
    if len(meta) != 1 or meta[0][0] != case_id or tuple(map(int, meta[0][2:])) != (M, K):
        raise ValueError('log metadata missing, repeated, or mismatched to vectors/seed')
    if '[RADAR] PASSED' not in text or '[RADAR] FAILED' in text:
        raise ValueError('firmware did not report PASSED')
    real, imag = np.zeros(M*K, np.uint16), np.zeros(M*K, np.uint16)
    seen = set()
    for idx, r, i in re.findall(r'\[BF16\]\s+(\d+)\s+([0-9a-fA-F]{4})\s+([0-9a-fA-F]{4})', text):
        idx = int(idx)
        if idx in seen or not 0 <= idx < M*K:
            raise ValueError('duplicate or out-of-range BF16 sample')
        seen.add(idx)
        real[idx], imag[idx] = int(r, 16), int(i, 16)
    if len(seen) != M*K:
        raise ValueError(f'incomplete dump: {len(seen)} of {M*K} samples')
    return (real.view(np.float16).reshape(M, K),
            imag.view(np.float16).reshape(M, K), meta[0][1])


def power_db(c):
    power = np.abs(c)**2
    return 10*np.log10(np.maximum(power / max(float(power.max()), 1e-30), 1e-5))


def plot_radar(path, data, actual=None, label='FP16 software model'):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    plt.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 10,
                         'axes.spines.top': False, 'axes.spines.right': False})
    c = (data['cr'].astype(float) + 1j*data['ci'].astype(float)
         if actual is None else actual)
    fig = plt.figure(figsize=(13, 9), layout='constrained', facecolor='#f5f7fb')
    gs = fig.add_gridspec(2, 2)
    ax = fig.add_subplot(gs[0, 0], projection='polar')
    ax.set_theta_zero_location('N')
    ax.set_theta_direction(-1)
    ax.set_thetamin(-74)
    ax.set_thetamax(74)
    edges = np.deg2rad(np.linspace(-72, 72, M+1))
    redges = np.arange(K+1)*25.0 + 12.5
    ax.grid(False)
    mesh = ax.pcolormesh(edges, redges, power_db(c).T, cmap='magma',
                         vmin=-45, vmax=0, shading='flat', rasterized=True)
    ax.grid(alpha=.25)
    ax.set_yticks([100, 200, 300, 400])
    ax.set_title('Synthetic radar view  |  receive beam scan', pad=22)
    for angle, rb, _, _ in TARGETS:
        ax.scatter(np.deg2rad(angle), RANGES[rb], marker='x', color='cyan', s=55)
    ax.set_rlabel_position(70)
    ax.set_ylabel('Assigned range (m)', labelpad=32)
    fig.colorbar(mesh, ax=ax, label='Power relative to scan maximum (dB)', shrink=.76)

    ax = fig.add_subplot(gs[0, 1])
    for angle, rb, _, _ in TARGETS:
        p = np.abs(c[:, rb])**2
        ax.plot(ANGLES, 10*np.log10(np.maximum(p/p.max(), 1e-5)),
                'o-', ms=3, label=f'{angle:+.0f}° / {RANGES[rb]:.0f} m')
        ax.axvline(angle, color='#667085', lw=.7, ls=':')
    ax.set(xlabel='Look angle from broadside (degrees)', ylabel='Normalized power (dB)',
           title='Direction recovery at the three target bins', ylim=(-45, 2))
    ax.legend(fontsize=9)
    ax.grid(alpha=.2)

    ax = fig.add_subplot(gs[1, 0])
    fine = np.linspace(-90, 90, 1801)
    steering = np.exp(1j*np.pi*np.arange(N)[:, None]*np.sin(np.deg2rad(fine)))
    for angle, _, _, _ in TARGETS:
        w = np.exp(-1j*np.pi*np.arange(N)*np.sin(np.deg2rad(angle)))/N
        response = np.abs(w @ steering)**2
        ax.plot(fine, 10*np.log10(np.maximum(response, 1e-5)), label=f'Steer {angle:+.0f}°')
    ax.set(xlabel='Arrival angle (degrees)', ylabel='Array gain (dB)',
           title='Beam formation  |  16 elements at half-wavelength spacing',
           xlim=(-80, 80), ylim=(-45, 2))
    ax.legend(fontsize=9)
    ax.grid(alpha=.2)

    ax = fig.add_subplot(gs[1, 1])
    err = np.abs(c - data['ideal'])
    im = ax.imshow(err, origin='lower', aspect='auto', cmap='viridis',
                    extent=[12.5, 412.5, -72, 72])
    ax.set(xlabel='Assigned range (m)', ylabel='Look angle (degrees)',
           title=f'{label}: absolute complex error vs float64')
    fig.colorbar(im, ax=ax, label='Absolute amplitude error', shrink=.8)
    fig.suptitle('ISOLDE / Ibex  •  complex GEMM radar beamforming\n'
                 f'36 look angles × 16 antennas × 16 range bins  |  {label}', fontsize=16)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=160)
    plt.close(fig)


def animate(path):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.animation import FuncAnimation, PillowWriter
    fig, ax = plt.subplots(figsize=(7, 5), subplot_kw={'projection': 'polar'}, layout='constrained')
    ax.set_theta_zero_location('N')
    ax.set_theta_direction(-1)
    ax.set_thetamin(-90)
    ax.set_thetamax(90)
    ax.set_ylim(0, 40)
    ax.set_yticks([0, 10, 20, 30, 40], ['−40', '−30', '−20', '−10', '0 dB'])
    theta = np.linspace(-90, 90, 721)
    manifold = np.exp(1j*np.pi*np.arange(N)[:, None]*np.sin(np.deg2rad(theta)))
    line, = ax.plot([], [], color='#2463eb', lw=2)
    direction, = ax.plot([], [], color='#f97316', ls='--')
    def frame(index):
        angle = ANGLES[index]
        w = np.exp(-1j*np.pi*np.arange(N)*np.sin(np.deg2rad(angle)))/N
        gain = 20*np.log10(np.maximum(np.abs(w @ manifold), .01))
        line.set_data(np.deg2rad(theta), gain + 40)
        direction.set_data([np.deg2rad(angle)]*2, [0, 40])
        ax.set_title(f'Receive beam steering: {angle:+.0f}°\n16 elements · half-wavelength spacing', pad=24)
        return line, direction
    animation = FuncAnimation(fig, frame, frames=M, interval=110)
    animation.save(path, writer=PillowWriter(fps=9), dpi=100)
    plt.close(fig)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--out-dir', type=Path, default=Path('results'))
    p.add_argument('--header', type=Path)
    p.add_argument('--onnx-dir', type=Path)
    p.add_argument('--rtl-log', type=Path)
    p.add_argument('--animate', action='store_true')
    p.add_argument('--seed', type=int, default=7)
    args = p.parse_args()
    data = prepare(args.seed)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    c = data['cr'].astype(float) + 1j*data['ci'].astype(float)
    report = dict(case_id=data['case_id'], seed=args.seed,
                  shape={'A': [M, N], 'B': [N, K], 'C': [M, K]},
                  block_shape=[BLOCK_M, N, K],
                  max_complex_error_vs_float64=float(np.max(np.abs(c-data['ideal']))),
                  rms_complex_error_vs_float64=float(np.sqrt(np.mean(np.abs(c-data['ideal'])**2))),
                  tolerance={'ulp': ULP_TOL, 'absolute': ABS_TOL, 'rule': 'ULP <= 4 OR absolute <= 2^-12; finite only'},
                  rtl_simulation_run=False, targets=[])
    for angle, rb, _, _ in TARGETS:
        recovered = float(ANGLES[np.argmax(np.abs(c[:, rb])**2)])
        report['targets'].append(dict(true_angle=angle, recovered_angle=recovered,
                                      range_bin=rb, assigned_range_m=float(RANGES[rb])))
        if abs(recovered-angle) > 4.0:
            raise RuntimeError(f'beamforming sign/layout check failed at {angle} degrees')
    if args.header:
        emit_header(args.header, data)
    if args.onnx_dir:
        report.update(export_onnx(args.onnx_dir, data))
    np.savez(args.out_dir / 'beamforming_vectors.npz', **data)
    plot_radar(args.out_dir / 'beamforming.png', data)
    if args.animate:
        animate(args.out_dir / 'beam_scan.gif')
    if args.rtl_log:
        real, imag, mode = parse_log(args.rtl_log, data['case_id'])
        report['rtl_log_validation'] = compare(real, imag, data)
        report['rtl_log_mode'] = mode
        # A parsed log can also be a host mock; keep provenance explicit.
        report['rtl_simulation_run'] = 'user-supplied log; verify simulator provenance'
        plot_radar(args.out_dir / 'beamforming_from_log.png', data,
                   real.astype(float) + 1j*imag.astype(float), f'Log output ({mode})')
    (args.out_dir / 'summary.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2))
    if report.get('rtl_log_validation', {}).get('errors', 0):
        raise SystemExit('RTL output differs from the FP16 reference')


if __name__ == '__main__':
    main()
