#!/usr/bin/env python3
"""
Gate-Level Netlist Wrapper Generator for Verilator
Converts Yosys gate-level netlist with flattened ports to RTL-style bundled ports
"""

import re
import sys
from collections import defaultdict
from typing import Dict, List, Tuple

class NetlistParser:
    def __init__(self, netlist_file: str):
        self.netlist_file = netlist_file
        self.module_name = ""
        self.ports = []  # List of (port_name, direction)
        self.port_directions = {}  # port_name -> direction
        
    def parse(self):
        """Parse the gate-level netlist to extract module name and ports"""
        with open(self.netlist_file, 'r') as f:
            content = f.read()
        
        # Extract module name
        module_match = re.search(r'module\s+(\w+)\s*\(', content)
        if module_match:
            self.module_name = module_match.group(1)
        else:
            raise ValueError("Could not find module declaration")
        
        # Extract port declarations
        # Match input/output declarations
        port_pattern = r'(input|output)\s+(\w+);'
        for match in re.finditer(port_pattern, content):
            direction = match.group(1)
            port_name = match.group(2)
            self.ports.append((port_name, direction))
            self.port_directions[port_name] = direction
        
        print(f"● Found module: {self.module_name}")
        print(f"● Found {len(self.ports)} ports")
        
        return self.module_name, self.ports, self.port_directions


class WrapperGenerator:
    def __init__(self, module_name: str, ports: List[Tuple[str, str]], 
                 port_directions: Dict[str, str]):
        self.module_name = module_name
        self.gl_module_name = module_name  # Gate-level module name
        self.wrapper_module_name = f"{module_name}_wrapper"
        self.ports = ports
        self.port_directions = port_directions
        self.bundled_ports = defaultdict(list)  # base_name -> [(index, full_name, direction)]
        self.scalar_ports = []  # [(port_name, direction)]
        
    def analyze_ports(self):
        """Analyze ports to identify vectors and scalars"""
        # Pattern to match: signal_name_<digit(s)>_
        vector_pattern = re.compile(r'^(.+?)_(\d+)_$')
        
        for port_name, direction in self.ports:
            match = vector_pattern.match(port_name)
            if match:
                base_name = match.group(1)
                index = int(match.group(2))
                self.bundled_ports[base_name].append((index, port_name, direction))
            else:
                self.scalar_ports.append((port_name, direction))
        
        # Sort bundled ports by index
        for base_name in self.bundled_ports:
            self.bundled_ports[base_name].sort(key=lambda x: x[0])
        
        print(f"● Found {len(self.bundled_ports)} bundled signals")
        print(f"● Found {len(self.scalar_ports)} scalar signals")
    
    def generate_wrapper(self, output_file: str):
        """Generate the SystemVerilog wrapper"""
        with open(output_file, 'w') as f:
            # Header
            f.write("// Auto-generated SystemVerilog wrapper for gate-level netlist\n")
            f.write("// Generated by netlist_wrapper_generator.py\n")
            f.write(f"// Original module: {self.gl_module_name}\n\n")
            
            # Module declaration
            f.write(f"module {self.wrapper_module_name} (\n")
            
            # Generate wrapper port list
            port_list = []
            
            # Add scalar ports
            for port_name, direction in self.scalar_ports:
                port_list.append(f"    {direction:6s} logic       {port_name}")
            
            # Add bundled ports
            for base_name in sorted(self.bundled_ports.keys()):
                ports_info = self.bundled_ports[base_name]
                direction = ports_info[0][2]  # All bits have same direction
                max_index = max(p[0] for p in ports_info)
                min_index = min(p[0] for p in ports_info)
                
                if min_index == 0:
                    port_list.append(f"    {direction:6s} logic [{max_index}:0] {base_name}")
                else:
                    port_list.append(f"    {direction:6s} logic [{max_index}:{min_index}] {base_name}")
            
            f.write(",\n".join(port_list))
            f.write("\n);\n\n")
            
            # Generate internal wires for gate-level connections
            f.write("    // Internal wires for gate-level netlist connections\n")
            
            # Wires for bundled signals
            for base_name in sorted(self.bundled_ports.keys()):
                ports_info = self.bundled_ports[base_name]
                for index, gl_port_name, direction in ports_info:
                    f.write(f"    logic {gl_port_name};\n")
            
            f.write("\n")
            
            # Generate assignments for bundled signals
            f.write("    // Bundle/unbundle vector signals\n")
            for base_name in sorted(self.bundled_ports.keys()):
                ports_info = self.bundled_ports[base_name]
                direction = ports_info[0][2]
                
                for index, gl_port_name, _ in ports_info:
                    if direction == "output":
                        # Gate-level output -> wrapper output
                        f.write(f"    assign {base_name}[{index}] = {gl_port_name};\n")
                    else:  # input
                        # Wrapper input -> gate-level input
                        f.write(f"    assign {gl_port_name} = {base_name}[{index}];\n")
            
            f.write("\n")
            
            # Instantiate gate-level netlist
            f.write("    // Gate-level netlist instantiation\n")
            f.write(f"    {self.gl_module_name} u_gate_level (\n")
            
            # Generate port connections
            connections = []
            
            # Scalar ports - direct connection
            for port_name, direction in self.scalar_ports:
                connections.append(f"        .{port_name}({port_name})")
            
            # Bundled ports - connect to individual wires
            for base_name in sorted(self.bundled_ports.keys()):
                ports_info = self.bundled_ports[base_name]
                for index, gl_port_name, direction in ports_info:
                    connections.append(f"        .{gl_port_name}({gl_port_name})")
            
            f.write(",\n".join(connections))
            f.write("\n    );\n\n")
            
            f.write("endmodule\n")
        
        print(f"⚠ Wrapper generated: {output_file}")
        print(f"⚠ Wrapper module name: {self.wrapper_module_name}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 gen_wrapper.py <gate_level_netlist.v> [output_wrapper.sv]")
        print("Example: python3 gen_wrapper.py rv_top_gl.v rv_top_wrapper.sv")
        sys.exit(1)
    
    netlist_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "wrapper.sv"
    
    # Parse netlist
    parser = NetlistParser(netlist_file)
    module_name, ports, port_directions = parser.parse()
    
    # Generate wrapper
    generator = WrapperGenerator(module_name, ports, port_directions)
    generator.analyze_ports()
    generator.generate_wrapper(output_file)
    
    print("\n✅ Wrapper generation complete!")
#    print(f"\nNext steps:")
#    print(f"1. Include the gate-level netlist and wrapper in your Verilator compilation")
#   print(f"2. Use '{generator.wrapper_module_name}' as your top module")
#    print(f"3. Compile with: verilator --cc {output_file} {netlist_file} --top-module {generator.wrapper_module_name}")


if __name__ == "__main__":
    main()
