// Generated by VIO - August 10, 2026

#ifndef __OMP_REDMULE_H__
#define __OMP_REDMULE_H__
#include <bsp/simple_system_common.h>
#include <bsp/spm.h>

#define REDMULE_BIT(t)  (1u << (t))

// ---- async launch: select tile, load operands, fire. Does NOT wait. ----
#define redmule_gemm_async(t, x, w, y, N, M, K)                      \
  do {                                                               \
    isolde_set_tile(t);                                             \
    register uint32_t _x asm("t0") = (x);                          \
    register uint32_t _w asm("t1") = (w);                          \
    register uint32_t _y asm("t2") = (y);                          \
    asm volatile("redmule.gemm t0,t1,t2," #N "," #M "," #K         \
                 :: "r"(_x),"r"(_w),"r"(_y) : "memory");           \
  } while (0)

// ---- Q1: which device is free? (scheduler / dispatch) ----
static inline int redmule_alloc_tile(uint32_t pool) {
    uint32_t free = (~isolde_get_tile_status()) & pool;
    return free ? __builtin_ctz(free) : -1;
}

// ---- Q2: which device woke me? (join) — race-free, W1C ----
static inline void redmule_wait_all(uint32_t mask) {
    isolde_set_intr_en(mask);
    uint32_t done = 0;
    while ((done & mask) != mask) {
        uint32_t ip = isolde_get_tile_ip() & mask;
        if (ip) { isolde_clear_tile_ip(ip); done |= ip; }
        else    asm volatile("wfi" ::: "memory");   // sticky IP -> no missed wake
    }
}

// ---- upload/download helpers (TILESEL steers the HW router) ----
static inline uint32_t redmule_upload(int t, uint32_t at,
                                      const uint32_t *src, uint32_t elems) {
    isolde_set_tile(t);
    return spm_write(at, (uint32_t*)src, elems);
}
static inline void redmule_download(int t, uint32_t *dst,
                                    uint32_t at, uint32_t elems) {
    isolde_set_tile(t);
    spm_read(dst, at, elems);
}
#endif
