# Verilator waivers

# Waive the "unoptimized flattening" warning
-Wno-UNOPTFLAT
-Wno-CASEINCOMPLETE
-Wno-UNSIGNED
#-Wno-UNUSEDPARAM
#-Wno-UNUSEDSIGNAL
#-Wno-UNDRIVEN
-Wno-WIDTHEXPAND
-Wno-WIDTHTRUNC
-Wno-ASCRANGE
-Wno-UNUSEDGENVAR
#-Wno-BLKSEQ
#-Wno-LATCH
#-Wno-COMBDLY
-Wno-IMPORTSTAR
-Wno-VARHIDDEN
-Wno-IMPLICIT
-Wno-GENUNNAMED
#-Wno-PINMISSING
-Wno-DECLFILENAME
-Wno-REDEFMACRO
-Wno-EOFNEWLINE
-Wno-SYNCASYNCNET
-Wno-MODDUP